"""
SC2 Arcade Signal Decoder
==========================
Parses the text-based journal signals used by the sc2-arcade-watcher system.
These signals are generated by a Battle.net protocol listener and represent
lobby lifecycle events.

Signal wire format (CRLF-terminated lines):
    KIND:VERSION\x01TIMESTAMP\x01FIELD1\x01FIELD2...

Delimiter hierarchy:
    \x01 - top-level field separator
    \x02 - slot list separator
    \x03 - per-slot field separator
    \x04 - profile field separator within a slot
"""

from __future__ import annotations
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


SEP1 = "\x01"
SEP2 = "\x02"
SEP3 = "\x03"
SEP4 = "\x04"


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class SignalKind(str, Enum):
    INIT = "INIT"   # session initialised
    TMCR = "TMCR"   # time correction
    QUIT = "QUIT"   # clean shutdown
    DISC = "DISC"   # disconnect
    LBLR = "LBLR"   # lobby list request (client→server)
    LBLS = "LBLS"   # lobby list (count)
    LBCR = "LBCR"   # lobby created
    LBRM = "LBRM"   # lobby removed
    LBUD = "LBUD"   # lobby updated (name/host/slots changed)
    LBPV = "LBPV"   # lobby preview (basic slot data)
    LBPA = "LBPA"   # lobby alive (heartbeat)
    LBPR = "LBPR"   # lobby preview request
    LBPE = "LBPE"   # lobby preview extended (with Battle.net profiles)


class SlotKind(int, Enum):
    OPEN    = 0
    AI      = 1
    HUMAN   = 2
    CLOSED  = 3


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class PlayerProfile:
    region_id:      int
    realm_id:       int
    profile_id:     int
    discriminator:  Optional[int] = None
    name:           Optional[str] = None


@dataclass
class LobbySlot:
    kind:       SlotKind
    team:       int
    name:       str
    profile:    Optional[PlayerProfile] = None


@dataclass
class SignalBase:
    kind:      SignalKind
    version:   int
    timestamp: float


@dataclass
class SignalInit(SignalBase):
    bucket_id:    str = ""
    player_handle: str = ""


@dataclass
class SignalLbls(SignalBase):
    count: int = 0


@dataclass
class SignalLbcr(SignalBase):
    lobby_id:         str = ""
    map_handle:       str = ""
    ext_mod_handle:   str = ""
    multi_mod_handle: str = ""
    map_variant_idx:  int = 0
    lobby_name:       str = ""
    host_name:        str = ""
    slots_humans_taken: int = 0
    slots_humans_total: int = 0


@dataclass
class SignalLbrm(SignalBase):
    lobby_id: str = ""


@dataclass
class SignalLbud(SignalBase):
    lobby_id:           str = ""
    lobby_name:         Optional[str] = None
    host_name:          Optional[str] = None
    slots_humans_taken: Optional[int] = None
    slots_humans_total: Optional[int] = None


@dataclass
class SignalLbpv(SignalBase):
    lobby_id:     str = ""
    slots:        list[LobbySlot] = field(default_factory=list)
    host_index:   int = 0
    teams_number: int = 0


@dataclass
class SignalLbpa(SignalBase):
    lobby_id: str = ""


@dataclass
class SignalLbpe(SignalBase):
    lobby_id:   str = ""
    slots:      list[LobbySlot] = field(default_factory=list)
    host_index: int = 0


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

class SignalDecodeError(Exception):
    pass


def _unescape(s: str) -> str:
    """Reverse backslash-escaping used for lobby names that contain delimiters."""
    return s.replace("\\n", "\n").replace("\\\\", "\\")


def _parse_slot_basic(raw: str) -> LobbySlot:
    """Parse a slot from LBPV: 'kind\x03team\x03name'"""
    parts = raw.split(SEP3)
    if len(parts) < 3:
        raise SignalDecodeError(f"Bad slot data: {raw!r}")
    return LobbySlot(
        kind=SlotKind(int(parts[0])),
        team=int(parts[1]),
        name=parts[2],
    )


def _parse_slot_extended(raw: str) -> LobbySlot:
    """Parse a slot from LBPE: 'kind\x03team\x03name[\x04region\x04realm\x04profileId\x04discriminator\x04name]'"""
    parts = raw.split(SEP3)
    if len(parts) < 3:
        raise SignalDecodeError(f"Bad extended slot data: {raw!r}")

    slot = LobbySlot(
        kind=SlotKind(int(parts[0])),
        team=int(parts[1]),
        name=parts[2],
    )

    if len(parts) > 3 and parts[3]:
        prof_fields = parts[3].split(SEP4)
        if len(prof_fields) >= 3:
            slot.profile = PlayerProfile(
                region_id=int(prof_fields[0]),
                realm_id=int(prof_fields[1]),
                profile_id=int(prof_fields[2]),
                discriminator=int(prof_fields[3]) if len(prof_fields) > 3 and prof_fields[3] else None,
                name=prof_fields[4] if len(prof_fields) > 4 else None,
            )
    return slot


def decode_line(line: str) -> Optional[SignalBase]:
    """
    Decode one CRLF-stripped journal line into a typed signal object.
    Returns None for unrecognised kinds or empty lines.
    """
    line = line.strip()
    if not line:
        return None

    # Split header from payload
    parts = line.split(SEP1)
    if not parts:
        return None

    header = parts[0]
    payload = parts[1:]

    # Parse KIND:VERSION
    m = re.match(r"^([A-Z]+)(?::(\d+))?$", header)
    if not m:
        raise SignalDecodeError(f"Bad signal header: {header!r}")

    try:
        kind = SignalKind(m.group(1))
    except ValueError:
        return None  # unknown kind — skip

    version   = int(m.group(2)) if m.group(2) else 1
    timestamp = float(payload[0]) if payload else 0.0
    args      = payload[1:]

    base_kwargs = dict(kind=kind, version=version, timestamp=timestamp)

    def arg(i: int, default="") -> str:
        return args[i] if i < len(args) else default

    def iarg(i: int, default=0) -> int:
        v = arg(i)
        return int(v) if v else default

    if kind == SignalKind.INIT:
        return SignalInit(
            **base_kwargs,
            bucket_id=arg(0),
            player_handle=arg(1),
        )

    elif kind == SignalKind.LBLS:
        return SignalLbls(**base_kwargs, count=iarg(0))

    elif kind == SignalKind.LBCR:
        return SignalLbcr(
            **base_kwargs,
            lobby_id=arg(0),
            map_handle=arg(1),
            ext_mod_handle=arg(2),
            multi_mod_handle=arg(3),
            map_variant_idx=iarg(4),
            lobby_name=_unescape(arg(5)),
            host_name=arg(6),
            slots_humans_taken=iarg(7),
            slots_humans_total=iarg(8),
        )

    elif kind == SignalKind.LBRM:
        return SignalLbrm(**base_kwargs, lobby_id=arg(0))

    elif kind == SignalKind.LBUD:
        return SignalLbud(
            **base_kwargs,
            lobby_id=arg(0),
            lobby_name=_unescape(arg(1)) if arg(1) else None,
            host_name=arg(2) if arg(2) else None,
            slots_humans_taken=int(arg(3)) if arg(3) else None,
            slots_humans_total=int(arg(4)) if arg(4) else None,
        )

    elif kind == SignalKind.LBPV:
        raw_slots = arg(0).split(SEP2) if arg(0) else []
        slots = [_parse_slot_basic(s) for s in raw_slots if s]
        # Filter out CLOSED slots (kind=3)
        slots = [s for s in slots if s.kind != SlotKind.CLOSED]
        return SignalLbpv(
            **base_kwargs,
            lobby_id=arg(1) if len(args) > 1 else "",
            slots=slots,
            host_index=iarg(2),
            teams_number=iarg(3),
        )

    elif kind == SignalKind.LBPA:
        return SignalLbpa(**base_kwargs, lobby_id=arg(0))

    elif kind == SignalKind.LBPE:
        raw_slots = arg(0).split(SEP2) if arg(0) else []
        slots = [_parse_slot_extended(s) for s in raw_slots if s]
        slots = [s for s in slots if s.kind != SlotKind.CLOSED]
        return SignalLbpe(
            **base_kwargs,
            lobby_id=arg(1) if len(args) > 1 else "",
            slots=slots,
            host_index=iarg(2),
        )

    elif kind in (SignalKind.LBLR, SignalKind.LBPR, SignalKind.QUIT,
                  SignalKind.DISC, SignalKind.TMCR):
        return SignalBase(**base_kwargs)

    return None


def decode_stream(lines: list[str]) -> list[SignalBase]:
    """Decode a list of journal lines into signals, skipping errors."""
    results = []
    for i, line in enumerate(lines):
        try:
            sig = decode_line(line)
            if sig:
                results.append(sig)
        except SignalDecodeError as e:
            print(f"[warn] line {i}: {e}")
    return results
